server:
  adminMinThreads: 1
  adminMaxThreads: 10
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /}
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  applicationConnectors:
    - type: ${APPLICATION_CONNEXTOR_TYPE:- http}
      port: ${APPLICATION_CONNEXTOR_PORT:- 8899}
  adminConnectors:
    - type: ${ADMIN_CONNEXTOR_TYPE:- http}
      port: ${ADMIN_CONNEXTOR_PORT:- 8900}

database:
  driverClass: org.mariadb.jdbc.Driver
  user: ${DB_USER:- stroomuser}
  password: ${DB_PASSWORD:- stroompassword1}
  url: ${DB_URL:- jdbc:mariadb://localhost:3310/annotations}
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.show_sql: false
    hibernate.hbm2ddl.auto: validate

logging:
  level: ${LOGGING_LEVEL:- ERROR}
  loggers:
    stroom: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
    "AUDIT":
      level: INFO
      appenders:
        - type: fifo
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

token:
  publicKeyUrl: http://localhost:10080/testAuthService/publicKey
  jwsIssuer: stroom
  algorithm: RS256


authorisationService:
  url: http://localhost:10080/api/authorisation/v1
  isAuthorisedPath: /isAuthorised